### ISSUE TITLE
yass2dotplot.php

### ISSUE THREAD

**Issue by stanislasmorand** [laurentnoe/yass#4]
Bonsoir Mr Noé,
Je viens d'installer et compiler Yass et réussi avec succès un premier test (**yass file1.fa  file2.fa > output.yop**)
J'ai voulu ensuite générer le dotplot correspondant au résultat  (**./yass2dotplot.php output.yop  filename1="file1"  filename2="file2"**) mais une erreur est apparue: **-bash: ./yass2dotplot.php: Permission non accordée**
Je débute sous Linux, aussi je pense qu'il s'agit plutôt d'une erreur de mon environnement système... Si vous avez une idée, je suis preneur. Je vous joins le fichier yass2dotplot.php que j'utilise.
[yass2dotplot.php.txt](https://github.com/laurentnoe/yass/files/5380705/yass2dotplot.php.txt)
Merci par avance de votre aide et temps précieux.
Cdlt,
Stanislas Morand

**Comment by stanislasmorand** [comment]
Résolu avec le recours à un petit chmod +x

**Comment by laurentnoe** [comment]
;-)
