### ISSUE TITLE
yass2dotplot

### ISSUE THREAD

**Issue by Gon1976** [laurentnoe/yass#6]
I want to make the dotplot after yass
I have this error:

command: ../yass/yass2dotplot.php Prueba
/usr/bin/env: ‘php’: No such file or directory

I need to install something more?
thanks

**Comment by laurentnoe** [comment]
php (i dont know which one could be installed on your computer) :  

-   `apt-cache search php` or `apt-cache search php[0-9]\.[0-9]`on ubuntu could help (use `sudo apt-get install <the_right_package>` after) 👍

-   `apt-cache  search php*-gd` with a similar install procedure

**Comment by Gon1976** [comment]
solved!
