### ISSUE TITLE
Issue with yass2dotplot.php (ImageCreate)

### ISSUE THREAD

**Issue by davidenoma** [laurentnoe/yass#7]
Fatal error: Uncaught Error: Call to undefined function ImageCreate() in /home/dnanexus/yass/yass2dotplot.php:236
Stack trace:
#0 {main}
  thrown in /home/dnanexus/yass/yass2dotplot.php on line 236

**Comment by laurentnoe** [comment]
Possibly solved in 
https://stackoverflow.com/questions/3106991/fatal-error-call-to-undefined-function-imagecreate
?

**Comment by laurentnoe** [comment]
👍  New in `[yass2dotplot.php](https://github.com/laurentnoe/yass/blob/master/yass2dotplot.php)` :  there is now a possibility to output `svg` files ... and not only `png` files. 

this will also help people having problems installing the `php-gd` library
